VCST-1555: Minor improvements and bugfixes
VirtoCommerce/vc-module-skyflow pull request #10
Opened 2024-07-23 14:27 UTC by tatarincev

## Description

## References
### QA-test:
### Jira-link:
https://virtocommerce.atlassian.net/browse/VCST-1555

### Artifact URL:
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Skyflow_3.807.0-pr-10-c860.zip

2024-07-23 14:32 UTC, artem-dudarev requested changes

2024-07-23 14:32 UTC, artem-dudarev commented on src/VirtoCommerce.Skyflow.XApi/Queries/SkyflowCardQueryBuilder.cs
> +    }
This override doesn't change the base behavior

2024-07-23 17:46 UTC, artem-dudarev requested changes

2024-07-23 17:46 UTC, artem-dudarev commented on src/VirtoCommerce.Skyflow.XApi/Queries/SkyflowCardQueryBuilder.cs
> +using GraphQL;
Undo

2024-07-23 17:46 UTC, artem-dudarev commented on src/VirtoCommerce.Skyflow.XApi/Queries/SkyflowCardQueryBuilder.cs
> +    }
Undo

2024-07-23 17:46 UTC, artem-dudarev commented on src/VirtoCommerce.Skyflow.Data/Services/SkyflowClient.cs
> +            var pairs = props.Select(x => x.Name + "=" + x.GetValue(callParams, null)).ToArray();
Name and value should be encoded.
Use [Microsoft.AspNetCore.Http.Extensions.QueryBuilder](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.extensions.querybuilder?view=aspnetcore-8.0).

2024-07-25 08:30 UTC, artem-dudarev approved these changes

2024-07-25 09:38 UTC, merged

2024-07-29 12:56 UTC, ekuvirto commented
https://github.com/VirtoCommerce/vc-module-skyflow/releases/tag/3.805.1